server.port=8080

# oAuth server settings
oauth.server.address=http://localhost:9090

# OAuth server public part of secret for decode
# just imagine, that we use private/public keys instead of simple string
config.oauth.public_secret=do_your_best_mate!
config.oauth.active.aud=rs-server
config.oauth.time.skew.sec=5
